version: '3.9'

services:

  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  
  # Node API service
  api:
    build: .
    container_name: api
    hostname: api
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://mongo_db:27017/mint
      JWT_SECRET: HotWater
    depends_on:
      - mongo_db

  # Nginx service
  nginx:
    build:
      context: ./nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      # - ./certbot/www:/var/www/certbot/:ro
    depends_on:
      - api

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  mongo_db: {}